### ISSUE TITLE
Spacing in 'About ' Section

### ISSUE THREAD

**Issue by perezjprz19** [perezjprz19/my-portfolio#2]
The 'About' section is too close to the 'Projects' section. Can there be more space between the two sections?

The contact form is also too close to the 'About' section. There should be more space between the two so that when the user clicks on the 'About' link at the top of the page, they don't also see the contact form too, since that has its own link.

**Comment by CKMolinga** [comment]
Hello there 👋. You may want to have a div with a class of "spacing" (which is assigned a height) after each section to achieve a desirable spacing after each section. You can also give each section an id, and then reference your nav links to the ids of the corresponding sections.
Tip: For smooth scroll, use;
"html {
  scroll-behavior: smooth;
}

**Comment by perezjprz19** [comment]
> Hello there 👋. You may want to have a div with a class of "spacing" (which is assigned a height) after each section to achieve a desirable spacing after each section. You can also give each section an id, and then reference your nav links to the ids of the corresponding sections. Tip: For smooth scroll, use; "html { scroll-behavior: smooth; }

Thank you for the suggestions. I did add the smooth scrolling as you suggested. I did already have the nav-links set up like you said, but for the spacing I opted to just use margins.  It seems to be fixed now. I'll keep the divs with height in mind for future projects though. Thanks again for your input. Very much appreciated!

**Comment by CKMolinga** [comment]
Ok, that's great you got it figured out
